### ISSUE TITLE
[Question] Nvidia and Gnome on Wayland

### ISSUE THREAD

**Issue by jeffshee** [negativo17/nvidia-driver#59]
Hi! 
I'm experiencing screen tearing problem on Xorg. It will be nice if I can switch to Wayland, while still be able to use proprietary Nvidia driver. I thought following the steps listed here [https://copr.fedorainfracloud.org/coprs/mati865/mutter-eglstream/](https://copr.fedorainfracloud.org/coprs/mati865/mutter-eglstream/) would be enough for everything to work on Wayland, but it seems I still lack something.

nvidia-settings
```ERROR: Unable to find display on any available system```

mutter --wayland
```Can't initialize KMS backend: Could not get session ID: No such file or directory```

DRI_PRIME=1 inxi -G
```
Graphics:
  Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel 
  Device-2: NVIDIA GM107M [GeForce GTX 950M] driver: nvidia v: 396.45 
  Display: wayland server: Fedora Project X.org 11.0 
  driver: modesetting,nvidia unloaded: nouveau resolution: 1920x1080~60Hz 
  OpenGL: renderer: llvmpipe (LLVM 6.0 256 bits) v: 3.3 Mesa 18.0.5 
```

DRI_PRIME=1 glxinfo | grep vendor
```
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
OpenGL vendor string: VMware, Inc.
```

Doesn't this mean that Nvidia isn't being used on Wayland? Sorry I'm quite new about these... Please kindly advise.
